# Generated by Django 5.1.7 on 2025-04-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h1', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
