# Generated by Django 5.1.7 on 2025-04-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h1', '0006_job_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stucomp',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
