# Generated by Django 5.1.7 on 2025-04-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h1', '0007_alter_stucomp_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stucomp',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stucomp',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
