# Generated by Django 5.1.7 on 2025-04-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h1', '0008_alter_stucomp_password_alter_stucomp_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stucomp',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
